### ISSUE TITLE
Consider swapping the generic parameters on ContainerViewController

### ISSUE THREAD

**Issue by bencochran** [square/workflow-swift#6]
`ContainerViewController` is currently `ContainerViewController<Output, Rendering>` whereas `AnyWorkflow` is `AnyWorkflow<Rendering, Output>`. This inconsistency has tripped me up a few times, and I don’t personally see a concrete reason for this ordering over the other. If we want to make these match, pre-1.0’s the time.

**Comment by AquaGeek** [comment]
I'd be fine changing this to make them consistent. Any thoughts, @dhavalshreyas?

FYI, we have **55 usages** of this internally, so not terrible to migrate.
